#make para compilar o programa escreva

CC =  gcc
FRAGS = -Wall -Wextra -Werror -g -std=99

TARGET = hello

Main: main.c escreva.c escreva.h
	$(CC) $(FLAGS) main.c escreva.c -o hello

clean: 
	rm -f *.o $(TARGET)